// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOTjJoi7xENH_vVKTh67NXqgYtW63taRo',
    appId: '1:604190194950:web:d223bdca6085b8563c3287',
    messagingSenderId: '604190194950',
    projectId: 'ibundiksha',
    authDomain: 'ibundiksha.firebaseapp.com',
    storageBucket: 'ibundiksha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACaIZ_4MsFDY4XbZf6MnspEs4FYZ9SKrI',
    appId: '1:604190194950:android:5e98cc03af5734853c3287',
    messagingSenderId: '604190194950',
    projectId: 'ibundiksha',
    storageBucket: 'ibundiksha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4rPfm66CPU7S-pf5um7DyV39QuSDfIHY',
    appId: '1:604190194950:ios:0bfd40ef632efe533c3287',
    messagingSenderId: '604190194950',
    projectId: 'ibundiksha',
    storageBucket: 'ibundiksha.appspot.com',
    androidClientId: '604190194950-keehaprgu1c6tvvrcl4jpsh7a65bu3ck.apps.googleusercontent.com',
    iosClientId: '604190194950-2skao90200f6bfh5ncle70polufskbdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibundiksha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4rPfm66CPU7S-pf5um7DyV39QuSDfIHY',
    appId: '1:604190194950:ios:0bfd40ef632efe533c3287',
    messagingSenderId: '604190194950',
    projectId: 'ibundiksha',
    storageBucket: 'ibundiksha.appspot.com',
    androidClientId: '604190194950-keehaprgu1c6tvvrcl4jpsh7a65bu3ck.apps.googleusercontent.com',
    iosClientId: '604190194950-2skao90200f6bfh5ncle70polufskbdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibundiksha',
  );
}
